# Generated by Django 5.2.15 on 2026-08-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('type', models.CharField(choices=[('terms-of-service', 'Условия использования'), ('privacy-policy', 'Политика конфиденциальности')], max_length=64, primary_key=True, serialize=False, verbose_name='Тип')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
