# Generated by Django 5.2.12 on 2026-05-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots_hub', '0002_alter_telegrambotshub_microservice_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambotshub',
            name='url',
            field=models.CharField(max_length=255, unique=True, verbose_name='URL-адрес'),
        ),
    ]
