# Initially generated by Django 5.2.12 on 2026-05-28 22:23

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

import telegram_bots.hub.models

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from ..models import TelegramBotsHub
else:
    TelegramBotsHub = Any


def generate_telegram_tokens(
    apps: Apps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    telegram_bots_hub_model: type[TelegramBotsHub] = apps.get_model(
        'telegram_bots_hub', 'TelegramBotsHub'
    )

    for hub in telegram_bots_hub_model.objects.iterator():
        hub.telegram_token = telegram_bots.hub.models._generate_token()
        hub.save(update_fields=['telegram_token'])


class Migration(migrations.Migration):
    dependencies = [('telegram_bots_hub', '0003_alter_telegrambotshub_url')]
    operations = [
        migrations.AlterField(
            model_name='telegrambotshub',
            name='service_token',
            field=models.CharField(
                default=telegram_bots.hub.models._generate_token,
                max_length=64,
                unique=True,
                verbose_name='Токен сервиса',
            ),
        ),
        migrations.AddField(
            model_name='telegrambotshub',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
            ),
        ),
        migrations.AddField(
            model_name='telegrambotshub',
            name='telegram_token',
            field=models.CharField(
                default=telegram_bots.hub.models._generate_token,
                max_length=64,
                verbose_name='Telegram токен',
            ),
        ),
        migrations.RunPython(
            generate_telegram_tokens, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='telegrambotshub',
            name='telegram_token',
            field=models.CharField(
                default=telegram_bots.hub.models._generate_token,
                max_length=64,
                unique=True,
                verbose_name='Telegram токен',
            ),
        ),
        migrations.AlterField(
            model_name='telegrambotshub',
            name='microservice_token',
            field=models.CharField(
                default=telegram_bots.hub.models._generate_token,
                max_length=64,
                unique=True,
                verbose_name='Токен микросервиса',
            ),
        ),
    ]
