# Initially generated by Django 5.2.12 on 2026-06-02 11:03

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from ..models import TelegramBotsHub
else:
    TelegramBotsHub = Any


def delete_hubs(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    telegram_bots_hub_model: type[TelegramBotsHub] = apps.get_model(
        'telegram_bots_hub', 'TelegramBotsHub'
    )
    telegram_bots_hub_model.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        (
            'telegram_bots_hub',
            '0004_telegrambotshub_id_telegrambotshub_telegram_token_and_more',
        )
    ]
    operations = [
        migrations.RunPython(delete_hubs, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(model_name='telegrambotshub', name='url'),
        migrations.AddField(
            model_name='telegrambotshub',
            name='container_id',
            field=models.CharField(
                default=None, max_length=255, unique=True, verbose_name='Container ID'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegrambotshub',
            name='idle_start_date',
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name='Дата начала простоя'
            ),
        ),
    ]
