# Generated by Django 5.2.12 on 2026-06-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots_hub', '0005_remove_telegrambotshub_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegrambotshub',
            options={'verbose_name': 'Хаб', 'verbose_name_plural': 'Хабы'},
        ),
        migrations.AlterField(
            model_name='telegrambotshub',
            name='container_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='ID контейнера'),
        ),
    ]
