# Generated by Django 5.2.12 on 2026-05-24 23:37

import django.db.models.deletion
import telegram_bots.models.trigger
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0020_alter_telegrambot_api_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=telegram_bots.models.trigger._generate_webhook_token, max_length=64, verbose_name='Токен')),
                ('trigger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webhook', to='telegram_bots.trigger', verbose_name='Триггер')),
            ],
            options={
                'verbose_name': 'Webhook триггер',
                'verbose_name_plural': 'Webhook триггеры',
                'db_table': 'telegram_bot_trigger_webhook',
            },
        ),
    ]
