# Generated by Django 5.2.12 on 2026-05-24 22:11

import telegram_bots.models.telegram_bot
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0020_triggerwebhook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambot',
            name='api_token',
            field=models.CharField(error_messages={'unique': 'Telegram бот с таким API-токеном уже существует.'}, max_length=64, unique=True, validators=[telegram_bots.models.telegram_bot.validate_api_token], verbose_name='API-токен'),
        ),
    ]
