# Generated by Django 5.2.12 on 2026-06-06 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0021_triggerwebhook'),
        ('telegram_bots_hub', '0005_remove_telegrambotshub_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots', to='telegram_bots_hub.telegrambotshub', verbose_name='Хаб'),
        ),
    ]
