# Initially generated by Django 5.2.12 on 2026-06-14 09:50

import django.db.models.deletion
from django.db import migrations, models
from typing import TYPE_CHECKING
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.apps.registry import Apps

if TYPE_CHECKING:
    from ..models import Chat, User
from ..enums import ChatType


def create_chats(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    chat_model: type[Chat] = apps.get_model('telegram_bots', 'Chat')
    user_model: type[User] = apps.get_model('telegram_bots', 'User')

    chat_model.objects.bulk_create(
        chat_model(
            telegram_id=user.telegram_id,
            type=ChatType.PRIVATE,
            username=user.username,
            first_name=user.first_name,
            last_name=user.last_name,
        )
        for user in user_model.objects.iterator()
    )


class Migration(migrations.Migration):
    dependencies = [('telegram_bots', '0022_telegrambot_hub')]
    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('telegram_id', models.BigIntegerField(verbose_name='Telegram ID')),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('private', 'Приватный'),
                            ('group', 'Группа'),
                            ('supergroup', 'Супергруппа'),
                            ('channel', 'Канал'),
                        ],
                        max_length=16,
                        verbose_name='Тип',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name='Название'
                    ),
                ),
                (
                    'username',
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name='@username'
                    ),
                ),
                (
                    'first_name',
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name='Имя'
                    ),
                ),
                (
                    'last_name',
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name='Фамилия'
                    ),
                ),
                ('is_forum', models.BooleanField(default=False, verbose_name='Форум')),
                (
                    'is_direct_messages',
                    models.BooleanField(default=False, verbose_name='Прямые сообщения'),
                ),
                (
                    'telegram_bot',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='chats',
                        to='telegram_bots.telegrambot',
                        verbose_name='Telegram бот',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'db_table': 'telegram_bot_chat',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='chats',
            field=models.ManyToManyField(
                blank=True,
                related_name='users',
                to='telegram_bots.chat',
                verbose_name='Чаты',
            ),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(
                fields=['telegram_id'], name='telegram_bo_telegra_7b7093_idx'
            ),
        ),
        migrations.RunPython(create_chats, reverse_code=migrations.RunPython.noop),
    ]
