# Generated by Django 5.2.15 on 2026-08-06 18:05

import constructor_telegram_bots.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0023_chat_user_chats_chat_telegram_bo_telegra_7b7093_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequest',
            name='headers',
            field=constructor_telegram_bots.fields.StrictJSONField(allowed_types=(dict,), blank=True, max_length=2048, null=True, verbose_name='Заголовки'),
        ),
    ]
