# Generated by Django 5.2.15 on 2026-08-08 17:17

import django.core.validators
import django.db.models.deletion
import telegram_bots.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0024_alter_apirequest_headers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('x', models.FloatField(default=telegram_bots.models.base.generate_random_coordinate, verbose_name='Координата X')),
                ('y', models.FloatField(default=telegram_bots.models.base.generate_random_coordinate, verbose_name='Координата Y')),
                ('duration_seconds', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3600)], verbose_name='Длительность в секундах')),
                ('telegram_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='telegram_bots.telegrambot', verbose_name='Telegram бот')),
            ],
            options={
                'verbose_name': 'Таймер',
                'verbose_name_plural': 'Таймеры',
                'db_table': 'telegram_bot_timer',
            },
        ),
    ]
