# Generated by Django 5.2.15 on 2026-08-09 15:07

import django.db.models.deletion
import telegram_bots.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0025_timer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Randomizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('x', models.FloatField(default=telegram_bots.models.base.generate_random_coordinate, verbose_name='Координата X')),
                ('y', models.FloatField(default=telegram_bots.models.base.generate_random_coordinate, verbose_name='Координата Y')),
                ('telegram_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='randomizers', to='telegram_bots.telegrambot', verbose_name='Telegram бот')),
            ],
            options={
                'verbose_name': 'Рандомайзер',
                'verbose_name_plural': 'Рандомайзеры',
                'db_table': 'telegram_bot_randomizer',
            },
        ),
    ]
