# Initially generated by Django 5.2.15 on 2026-10-01 13:29

from django.apps.registry import Apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
import django.core.validators
from django.db import migrations, models
from django.db.models import F

from typing import TYPE_CHECKING


if TYPE_CHECKING:
    from ..models import BackgroundTask


def convert_days_to_seconds(
    apps: Apps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    background_task_model: type[BackgroundTask] = apps.get_model(
        'telegram_bots', 'BackgroundTask'
    )
    background_task_model.objects.update(interval=F('interval') * 86400)


def convert_seconds_to_days(
    apps: Apps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    background_task_model: type[BackgroundTask] = apps.get_model(
        'telegram_bots', 'BackgroundTask'
    )
    background_task_model.objects.update(interval=F('interval') / 86400)


class Migration(migrations.Migration):
    dependencies = [('telegram_bots', '0026_randomizer')]
    operations = [
        migrations.AddField(
            model_name='backgroundtask',
            name='status',
            field=models.CharField(
                choices=[('pending', 'Ожидание'), ('running', 'Выполнение')],
                default='pending',
                max_length=7,
                verbose_name='Статус',
            ),
        ),
        migrations.AlterField(
            model_name='backgroundtask',
            name='interval',
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(900),
                    django.core.validators.MaxValueValidator(2592000),
                ],
                verbose_name='Интервал',
            ),
        ),
        migrations.RunPython(
            convert_days_to_seconds, reverse_code=convert_seconds_to_days
        ),
    ]
