# Generated by Django 5.2.15 on 2026-08-01 23:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(blank=True, max_length=64, null=True, verbose_name='Бейдж')),
                ('badge_en', models.CharField(blank=True, max_length=64, null=True, verbose_name='Бейдж')),
                ('badge_uk', models.CharField(blank=True, max_length=64, null=True, verbose_name='Бейдж')),
                ('badge_ru', models.CharField(blank=True, max_length=64, null=True, verbose_name='Бейдж')),
                ('period_months', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Период в месяцах')),
                ('amount_stars_per_month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Сумма в Telegram Stars за месяц')),
            ],
            options={
                'verbose_name': 'Цена подписки',
                'verbose_name_plural': 'Цены подписок',
                'db_table': 'premium_subscription_price',
                'ordering': ['period_months'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateTimeField(verbose_name='Конец подписки')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'db_table': 'premium_subscription',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('paid', 'Оплачено'), ('failed', 'Отклонено'), ('expired', 'Истекло'), ('refunded', 'Возврат')], default='pending', max_length=8, verbose_name='Статус')),
                ('period_months', models.PositiveSmallIntegerField(verbose_name='Период в месяцах')),
                ('amount_stars', models.PositiveIntegerField(verbose_name='Сумма в Telegram Stars')),
                ('telegram_charge_id', models.CharField(default=None, max_length=255, null=True, verbose_name='Telegram Charge ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('paid_date', models.DateTimeField(blank=True, null=True, verbose_name='Оплачен')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('subscription', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='premium.subscription', verbose_name='Подписка')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Счёт за подписку',
                'verbose_name_plural': 'Счета за подписки',
                'db_table': 'premium_subscription_invoice',
            },
        ),
    ]
